# Generated by Django 5.2.4 on 2025-10-20 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('identificacion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='rifas/')),
                ('fecha_sorteo', models.DateField()),
                ('total_tickets', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['-fecha_sorteo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('comprado_en', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app1.participante')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app1.rifa')),
            ],
            options={
                'ordering': ['rifa', 'number'],
                'unique_together': {('rifa', 'number')},
            },
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
