# Generated by Django 5.2.4 on 2025-10-20 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_participante_rifa_ticket_delete_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rifa',
            name='foto',
        ),
        migrations.CreateModel(
            name='RifaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rifas/')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.rifa')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
