# Generated by Django 5.2.4 on 2025-10-20 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_rifa_foto_rifaimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('metodo_pago', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='app1.participante')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='app1.rifa')),
            ],
        ),
    ]
