# Generated by Django 5.2.4 on 2025-10-20 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to='app1.compra'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
