# Generated by Django 5.2.4 on 2025-10-21 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_value', models.CharField(max_length=500)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app1.paymentmethod')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
