# Generated by Django 5.2.4 on 2025-10-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_paymentmethodfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
