# Generated by Django 5.2.4 on 2025-10-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rifa_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
