# Generated by Django 5.2.4 on 2025-10-22 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_compra_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='winner_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rifa', to='app1.ticket'),
        ),
    ]
