# Generated by Django 5.2.4 on 2025-10-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rifa_winner_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
